# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: playwright-workflow trigerred by cron sheduler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  # Check to generate your cron syntax: https://crontab.guru/
  - cron: "5 4 * * *" # At 04:05 on every day

jobs:
  run-test-smoke:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Display text on console
      run: echo "Running second workflow for Playwright smoke tests"
    - name: install dependencies 
      run: npm ci
    - name: istall pw browser
      run: npx playwright install
    - name: run smoke tests
      run: npm run test:smoke
